site_name: "LinkML Model"
site_url: "https://linkml.io/linkml-model"
theme:
  name: material
  analytics:
    gtag: G-2SYBSJVZ23
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
plugins:
  - search
  - mermaid2
  - mike:
      alias_type: symlink
      canonical_version: latest
extra:
  version:
    provider: mike
#markdown_extensions:
#  - toc:
#      permalink: true
docs_dir: docs/source
site_dir: docs/build
nav:
  - About: docs/home.md
  - Specification:
    - Index: docs/specification/index.md
    - Preface: docs/specification/00preamble.md
    - Introduction: docs/specification/01introduction.md
    - Instances: docs/specification/02instances.md
    - Schema Datamodel: docs/specification/03schemas.md
    - Derived Schemas: docs/specification/04derived-schemas.md
    - Instance Validation: docs/specification/05validation.md
    - Mapping of Instances: docs/specification/06mapping.md
  - Appendix:
    - Metamodel Index: docs/index.md
    - Profiles:
      - MinimalSubset: docs/MinimalSubset.md
      - BasicSubset: docs/BasicSubset.md
      - SpecificationSubset: docs/SpecificationSubset.md
      - RelationalModelProfile: docs/RelationalModelProfile.md
      - ObjectOrientedProfile: docs/ObjectOrientedProfile.md
      - OwlProfile: docs/OwlProfile.md
