---
name: Codespell

on:
  pull_request:
    branches: [main]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Codespell
        uses: codespell-project/actions-codespell@v2.1
